[workspace]
authors = ["jodyphelan <jodyphelan@outlook.com>"]
channels = ["conda-forge"]
name = "ssi_pingme"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
hatch = ">=1.16.3,<2"
envyaml = ">=1.10.211231,<2"
fastapi = ">=0.128.1,<0.129"
fastcore = ">=1.12.11,<2"
uvicorn = ">=0.40.0,<0.41"
python = ">=3.14.3,<3.15"
pip = ">=26.0.1,<27"
requests = ">=2.32.5,<3"
