[workspace]
authors = ["jodyphelan <jodyphelan@outlook.com>"]
channels = ["conda-forge"]
name = "ssi_pingme"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
hatch = ">=1.16.3,<2"
envyaml = ">=1.10.211231,<2"
fastapi = ">=0.128.1,<0.129"
fastcore = ">=1.12.11,<2"
uvicorn = ">=0.40.0,<0.41"
python = ">=3.14.3,<3.15"
pip = ">=26.0.1,<27"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.7.1,<10"
mkdocstrings = ">=1.0.3,<2"
mkdocstrings-python = ">=2.0.1,<3"
azure-identity = ">=1.25.1,<2"
msgraph-sdk = ">=1.48.0,<2"
